sudo: false
language: go
go:
- tip
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
- make clean all test
after_success:
  - make coverage && $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci
